#!/usr/bin/env nix
#!nix shell --inputs-from . nixpkgs#bash nixpkgs#curl nixpkgs#jq nixpkgs#alejandra -c bash
# shellcheck shell=bash
set -euo pipefail

# Query supported targets
targets=$(nix eval --json --inputs-from . --apply builtins.attrNames nixpkgs#legacyPackages)

echo "Fetching index.json" >&2
index=$(curl -L https://ziglang.org/download/index.json | jq -c --argjson targets "$targets" '
    with_entries(.value = (
        [
            {_date : .value.date, _version: .value.version // .key},
            $targets[] as $target | {
                ($target): .value[$target | sub("-darwin$"; "-macos")] // empty | {
                    filename: .tarball | capture("/(?<f>[^/]+)$").f,
                    shasum,
                },
            }
        ] | add
    ))
')

json2nix() {
    nix-instantiate --eval --arg-from-stdin json --expr '{json}: builtins.fromJSON json' | alejandra -q
}
comment='# Autogenerated by update-releases.sh, do not modify'

echo "Generating stable.nix" >&2
stable=$(jq -cr 'del(.master) | [.[]] | sort_by(._date)' <<<"$index" | json2nix)
printf '%s\n' "$comment" "$stable" >releases/stable.nix

echo "Updating nightly.nix" >&2
nightly=$(nix eval --json --file releases/nightly.nix | jq -cr --argjson index "$index" '
    # Add latest nightly if it is newer than the current one
    if .[-1]._date != $index.master._date then
        . + [$index.master]
    end |
    # Check list is sorted
    if . != sort_by(._date) then
        error("Nightly releases are not sorted")
    end
' | json2nix)
printf '%s\n' "$comment" "$nightly" >releases/nightly.nix

echo "Fetching community mirror list" >&2
curl -Lo releases/community-mirrors.txt https://ziglang.org/download/community-mirrors.txt

echo "Generating commit message" >&2

releases_commit_msg=$(
    for f in releases/{stable,nightly}.nix; do
        git show HEAD:"$f" | nix eval --json -f- |
            jq --argjson new "$(nix eval --json -f "$f")" '
                (map({(._version): true}) | add) as $old |
                $new[]._version | if in($old) then empty end
            '
    done | jq -rs '"releases: add \(join(", "))"'
)

mirrors_commit_msg=$(
    git show HEAD:releases/community-mirrors.txt |
        jq -Rrs --rawfile new releases/community-mirrors.txt '
            (split("\n") | map({(.): true}) | add) as $old |
            $new | split("\n") | map(if in($old) then empty end) |
            "mirrors: add \(join(", "))"
        '
)

git commit -m "$releases_commit_msg" releases/{stable,nightly}.nix || :
git commit -m "$mirrors_commit_msg" releases/community-mirrors.txt || :
