#!/usr/bin/env nix
#!nix shell --inputs-from . nixpkgs#bash nixpkgs#curl nixpkgs#jq nixpkgs#alejandra -c bash
# shellcheck shell=bash
set -euo pipefail

# Query supported targets
targets=$(nix eval --json --inputs-from . --apply builtins.attrNames nixpkgs#legacyPackages)

source='https://github.com/silversquirl/zig-flake'

echo "Fetching zig index.json" >&2
index=$(curl --retry 3 -fL "https://ziglang.org/download/index.json?source=$source" | jq -c --argjson targets "$targets" '
    def to_zig_targets:
        sub("-darwin$"; "-macos") |
        sub("i686-"; "x86-") |
        sub("armv7l-"; "arm-", "armv7a-");

    with_entries(.value = (
        [
            {_date : .value.date, _version: .value.version // .key},
            ($targets[], "src") as $target | {
                ($target): .value[$target | to_zig_targets] // empty | {
                    filename: .tarball | capture("/(?<f>[^/]+)$").f,
                    shasum,
                },
            }
        ] | add
    ))
')

echo "Fetching zls index.json" >&2
zls_index=$(curl --retry 3 -fL "https://builds.zigtools.org/index.json?source=$source" | jq -c --argjson targets "$targets" '
    def to_zig_targets:
        sub("-darwin$"; "-macos") |
        sub("i686-"; "x86-") |
        sub("armv7l-"; "arm-", "armv7a-");

    with_entries(.value = (
        [
            {_date : .value.date, _version: .value.version // .key},
            ($targets[], "src") as $target | {
                ($target): .value[$target | to_zig_targets] // empty | {tarball, shasum}
            }
        ] | add
    ))
')

echo "Fetching zls for latest nightly" >&2
zls_nightly_url=$(jq -r '
    @uri "https://releases.zigtools.org/v1/zls/select-version?zig_version=\(.master._version)&compatibility=only-runtime&source=$source"
' <<<"$index")
echo "$zls_nightly_url"
zls_nightly=$(curl --retry 3 -fl "$zls_nightly_url" | jq -c --argjson targets "$targets" '
    def to_zig_targets:
        sub("-darwin$"; "-macos") |
        sub("i686-"; "x86-") |
        sub("armv7l-"; "arm-", "armv7a-");

    if .code == null then
        [
            {_date : .date, _version: .version},
            ($targets[], "src") as $target | {
                ($target): .[$target | to_zig_targets] // empty | {tarball, shasum}
            }
        ] | add
    else
        null
    end
')

json2nix() {
	nix-instantiate --eval --arg-from-stdin json --expr '{json}: builtins.fromJSON json' | alejandra -q
}
comment='# Autogenerated by update-releases.sh, do not modify'

echo "Generating stable.nix" >&2
stable=$(jq -cr 'del(.master) | [.[]] | sort_by(._date)' <<<"$index" | json2nix)
printf '%s\n' "$comment" "$stable" >releases/stable.nix

echo "Generating zls.nix" >&2
zls_stable=$(jq -cr '[.[]] | sort_by(._date)' <<<"$zls_index" | json2nix)
printf '%s\n' "$comment" "$zls_stable" >releases/zls.nix

echo "Updating nightly.nix" >&2
nightly=$(nix eval --json --file releases/nightly.nix | jq -cr --argjson index "$index" --argjson zls "$zls_nightly" '
    if .[-1]._date == $index.master._date then
        .[:-1] # Give priority to the freshly generated release
    end |
    . + [$index.master | ._zls = $zls] |

    # Check list is sorted
    if . != sort_by(._date) then
        error("Nightly releases are not sorted")
    end
' | json2nix)
printf '%s\n' "$comment" "$nightly" >releases/nightly.nix

echo "Fetching community mirror list" >&2
curl --retry 3 -fLo releases/community-mirrors.txt "https://ziglang.org/download/community-mirrors.txt?source=$source"
