# Autogenerated by update-releases.sh, do not modify
[
  {
    _date = "2025-08-13";
    _version = "0.15.0-dev.1519+dd4e25cf4";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.15.0-dev.1519+dd4e25cf4.tar.xz";
      shasum = "fe83c7ca585d375ad649bd22d76da3e83d61a1cd465b8e737c839ef5cb44f44f";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.15.0-dev.1519+dd4e25cf4.tar.xz";
      shasum = "75421d138aa17f3c6104b39ce5a2adef2fda933e58d6818a5f77ff3bde27c9bc";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.15.0-dev.1519+dd4e25cf4.tar.xz";
      shasum = "3bc50871c16d628d3717ed95829b47177eecb0f517a7a9061e6b860db18c719a";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.15.0-dev.1519+dd4e25cf4.tar.xz";
      shasum = "5c26cfa5e00be7c05cc5a73f2a1e45724044066fb62e05d9d1dd1cf9c3e2c2c4";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.15.0-dev.1519+dd4e25cf4.tar.xz";
      shasum = "26179d9fc1cb93c1e7fc2acb283f3a0ff17f2a57dda60e2f8d251c935472263a";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.15.0-dev.1519+dd4e25cf4.tar.xz";
      shasum = "ab6acf777cffe164b8636a2631f43cb45b4e2e057c15302b5093bdf360209bec";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.15.0-dev.1519+dd4e25cf4.tar.xz";
      shasum = "b23365e23487b1dfcdbe0b551d9ede361d78bfb959c31fa423717ded69c80375";
    };
  }
  {
    _date = "2025-08-14";
    _version = "0.15.0-dev.1552+b87b95868";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.15.0-dev.1552+b87b95868.tar.xz";
      shasum = "31a4110c3d5070192be76944ba18159a43ba1d86abc930a162b4d562c5517746";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.15.0-dev.1552+b87b95868.tar.xz";
      shasum = "2f583d9f9b3957209bbcef0d052fdde47b5b5598823879b210925863b25c867c";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.15.0-dev.1552+b87b95868.tar.xz";
      shasum = "e50088bcb721b38e2942e2345f5851cc710720adc9a2caf686cc6a530c3fa2ed";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.15.0-dev.1552+b87b95868.tar.xz";
      shasum = "8d56c7b990cc2851e119b5dc82271507c7285ccf6583cc79c62b809b59a137f0";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.15.0-dev.1552+b87b95868.tar.xz";
      shasum = "38aab57b554567f6ef5dce6fcbd7470d63b93decc2046ed022224c62db0e8ea2";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.15.0-dev.1552+b87b95868.tar.xz";
      shasum = "c8d5fd9df6f50db377f3791d2be876fa963c140645ed8412659adcdbd3e31396";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.15.0-dev.1552+b87b95868.tar.xz";
      shasum = "91284b7bca4b828cc1e9f769bc60de151f1fff8d0d4f162f04aab1c6c523e945";
    };
  }
  {
    _date = "2025-08-15";
    _version = "0.15.0-dev.1564+2761cc8be";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.15.0-dev.1564+2761cc8be.tar.xz";
      shasum = "949d8a14b3efc1a5cf4a8dad68c91f6c2bb8dc8087adaccf72cd250ea1e221a0";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.15.0-dev.1564+2761cc8be.tar.xz";
      shasum = "eea59d69dbd1789d471d24d157fe44765cdf0cd9de29520b103725b5fdd1a5e0";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.15.0-dev.1564+2761cc8be.tar.xz";
      shasum = "c27b1c006d5811b2087046c69cf72acf109b76d6bcc4883ce01bc9a377d772d1";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.15.0-dev.1564+2761cc8be.tar.xz";
      shasum = "62550ef3d80c3fab2c2c90c23de9b2025d0e32b6177502ddc9bafd4d9fb76ee9";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.15.0-dev.1564+2761cc8be.tar.xz";
      shasum = "10b1690c266e18b6fe1bc57c29aa16f1c68a5af14667152204936a8a3dece834";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.15.0-dev.1564+2761cc8be.tar.xz";
      shasum = "47dc2428c216f2823188db831b1578bc2f338acfa9b5aa3200b63feea042b53d";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.15.0-dev.1564+2761cc8be.tar.xz";
      shasum = "f6c23e66a15bfe1f2d1781a8d3604c275bee80318aa18cf139478baac114e2d1";
    };
  }
  {
    _date = "2025-08-16";
    _version = "0.15.0-dev.1572+47e652876";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.15.0-dev.1572+47e652876.tar.xz";
      shasum = "6c3d99c8a9c8b567f63e400410c5ba4657d6aaab29d26830ce49fa5f51762d0e";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.15.0-dev.1572+47e652876.tar.xz";
      shasum = "386625efc8acd102345a63f888af4d00cfe52c282fa4a85f48079503cd9f75d3";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.15.0-dev.1572+47e652876.tar.xz";
      shasum = "5433d0f14405eb373a226a9a28c578c233f53002fc27bb9f44bbcf5d40d10173";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.15.0-dev.1572+47e652876.tar.xz";
      shasum = "dc78cc1f669ce3ed3213709211578753b0f9187ece93f9a18a7483a4a922cc86";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.15.0-dev.1572+47e652876.tar.xz";
      shasum = "12f42dca99d32ce23fd8d8d8b09c9c0f056184519c642cf093e2ae6b84ed3b46";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.15.0-dev.1572+47e652876.tar.xz";
      shasum = "64c2c9a75a6d1e1058fb7789734156d0b63c9239177dd4037706f07361f5ce8f";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.15.0-dev.1572+47e652876.tar.xz";
      shasum = "ca047048d1ff5c1aaee481d52eeefce2d0d548b7a8518e8270902d6b11833cfa";
    };
  }
  {
    _date = "2025-08-17";
    _version = "0.15.0-dev.1593+399bace2f";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.15.0-dev.1593+399bace2f.tar.xz";
      shasum = "23a12dbe83a1cf646d6587ac3e68b4fa6579731fe66ea86c5edb1c0276ab55a6";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.15.0-dev.1593+399bace2f.tar.xz";
      shasum = "bc7b56bf9d046ec83675f7f89d67bd80601ebe70f2c545d15add9565040cd086";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.15.0-dev.1593+399bace2f.tar.xz";
      shasum = "a65fc43f7d982ff2c9e6b7767fbceb45298da4d938bfb71c50953c400e27622a";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.15.0-dev.1593+399bace2f.tar.xz";
      shasum = "63bf646a60f99679b0531e243705990bde1cebcdf1cd467773774da917626fbe";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.15.0-dev.1593+399bace2f.tar.xz";
      shasum = "d7b90ce3e0f4f5d86a36abd7ac38034528dbb1d222c8c93754d8aed0c080d85c";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.15.0-dev.1593+399bace2f.tar.xz";
      shasum = "1e34c9474529e23fe2b9fbc5e3e6a3eea995fb438e60d54553c9dc95b8338d3b";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.15.0-dev.1593+399bace2f.tar.xz";
      shasum = "c50b27c9108c8e5302a994dd5ce88dbf1b9e80994220a0f9dce5b8bef3ceb4ea";
    };
  }
  {
    _date = "2025-08-18";
    _version = "0.15.0-dev.1599+cf90a5e45";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.15.0-dev.1599+cf90a5e45.tar.xz";
      shasum = "9fd80d66c43d73f020c18d8819cf246aabaf87eed09270e726482a587d96387e";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.15.0-dev.1599+cf90a5e45.tar.xz";
      shasum = "f714a996e3668c6a146942981df68546bec9d827caf7106a04720a7dc4dd2bc3";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.15.0-dev.1599+cf90a5e45.tar.xz";
      shasum = "af8a71b156a63ef1172b305b0325e316191b4b248cf5b08bfc9fbfe9620b0f1e";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.15.0-dev.1599+cf90a5e45.tar.xz";
      shasum = "07c6c5d1753413ba1e7ef324a2e56723522b61174df8a071b4b0f6117f1467f5";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.15.0-dev.1599+cf90a5e45.tar.xz";
      shasum = "393a3e803b7666686616c6094c74423dd7fbcfc10c81698257c785f1242f750f";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.15.0-dev.1599+cf90a5e45.tar.xz";
      shasum = "49c934f37bcf8bf26d080b9d15b7e07f1bfb5e06757db3453f4ff383516048bc";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.15.0-dev.1599+cf90a5e45.tar.xz";
      shasum = "4023795420e84d8f13655335e54e49f22e3bfb2b6b0cc11406b20eef649f3fd8";
    };
  }
  {
    _date = "2025-08-19";
    _version = "0.15.1";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.15.1.tar.xz";
      shasum = "c4bd624d901c1268f2deb9d8eb2d86a2f8b97bafa3f118025344242da2c54d7b";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.15.1.tar.xz";
      shasum = "bb4a8d2ad735e7fba764c497ddf4243cb129fece4148da3222a7046d3f1f19fe";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.15.1.tar.xz";
      shasum = "339e2106496be70b614e32d444298216e676c36d08f5cd7bee3dd1dbd4567fd7";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.15.1.tar.xz";
      shasum = "7ca7a3e621436fb31d66a253132fc39574a13d2a1b4d8458af4f2e7c6e4374fe";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.15.1.tar.xz";
      shasum = "9919392e0287cccc106dfbcbb46c7c1c3fa05d919567bb58d7eb16bca4116184";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.15.1.tar.xz";
      shasum = "9714f8ac3d3dc908b1599837c6167f857c1efaa930f0cfa840699458de7c3cd0";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.15.1.tar.xz";
      shasum = "c61c5da6edeea14ca51ecd5e4520c6f4189ef5250383db33d01848293bfafe05";
    };
  }
  {
    _date = "2025-08-21";
    _version = "0.16.0-dev.9+8248597a2";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.16.0-dev.9+8248597a2.tar.xz";
      shasum = "2a5ecb1ab98308c1738e086bcfa9c5c94d22d779b61feddc7925b5c15277fd04";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.16.0-dev.9+8248597a2.tar.xz";
      shasum = "5f1a5d8689113d908d61cfaaf9da46d0b5d7997595b10bc50bb1e34acfafe945";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.16.0-dev.9+8248597a2.tar.xz";
      shasum = "c3d198473b095719055fd1ea7d76a7994d2e721cb207b144da04b01b9e5390f8";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.16.0-dev.9+8248597a2.tar.xz";
      shasum = "013617e02586ada59dc468b35f39db3fd1805b8a2492720644e25ac793e01bbd";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.16.0-dev.9+8248597a2.tar.xz";
      shasum = "bb6f423cdf96ff2715680db97806c9683d5359d3f540658f596385581c23dfb6";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.16.0-dev.9+8248597a2.tar.xz";
      shasum = "f85e3375f0403107fc1170fba1ca5b223ec4c4b7a665bfb361bda368eb9bd904";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.16.0-dev.9+8248597a2.tar.xz";
      shasum = "a96553ff35df322e1deaf9292d4b677db1900eeac7aa511fa026300086c228d5";
    };
  }
  {
    _date = "2025-08-22";
    _version = "0.16.0-dev.13+1594c8055";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.16.0-dev.13+1594c8055.tar.xz";
      shasum = "031ce5bab0a47833b43bcc5466fd4be16f9741fbb140ac134f74200770cd7128";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.16.0-dev.13+1594c8055.tar.xz";
      shasum = "08b8959fe9e0819fbfc2bcc8d780ae55d66ea79eecf40dd56d86b8f793af4118";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.16.0-dev.13+1594c8055.tar.xz";
      shasum = "d3e98c2549a2f732d4f1b78c42a60afc933f0bf8c9875432a905d9eff6d83e5b";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.16.0-dev.13+1594c8055.tar.xz";
      shasum = "7cc64e99994558cb100c4233670789986309290a934be91e1a2ec008628417f4";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.16.0-dev.13+1594c8055.tar.xz";
      shasum = "09ec8c6872b2d122910baf0590617ace5ad0351d7d56449968981e98ae731f00";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.16.0-dev.13+1594c8055.tar.xz";
      shasum = "e32a7de12adbb70befb16e92e0098d53042a8c141cd8b6e16499664c011962a1";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.16.0-dev.13+1594c8055.tar.xz";
      shasum = "4c72e8f1d6a75d0e0d4d479bf1f47a17b89a912653c05154b6c53d180dbf0e66";
    };
  }
  {
    _date = "2025-08-23";
    _version = "0.16.0-dev.23+47a2f2dda";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.16.0-dev.23+47a2f2dda.tar.xz";
      shasum = "3717a05d15a1238a2a14a621777967438459e8eb3954ccfc3d2add86f46d66f1";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.16.0-dev.23+47a2f2dda.tar.xz";
      shasum = "a901e0a8a425b797ffd8e94705edc1f14227b61df26dc39e7b3af9687a837284";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.16.0-dev.23+47a2f2dda.tar.xz";
      shasum = "278242485c807bb04c92b690fa51cb94bacb0ffdedc97e75e6216b376255d9ec";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.16.0-dev.23+47a2f2dda.tar.xz";
      shasum = "09d9ccc1bc197fc3d1b1b1d41595457bcd517d2608d925d274ee779ce62d0ef5";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.16.0-dev.23+47a2f2dda.tar.xz";
      shasum = "0ef8e7eeb5142ea3607c4c30c881d866ad634fb9fde4845ad9bf232b930e90c8";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.16.0-dev.23+47a2f2dda.tar.xz";
      shasum = "3bfcd2734235836c4199b4c3f39cd8836fd9aca81ffc74a87829a26e74b9e506";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.16.0-dev.23+47a2f2dda.tar.xz";
      shasum = "fbcbc8b24c456d7bcb4a2bbfb9fbe903cc1513174e71fac1fdf585966b782dd0";
    };
  }
  {
    _date = "2025-08-24";
    _version = "0.16.0-dev.27+83f773fc6";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.16.0-dev.27+83f773fc6.tar.xz";
      shasum = "75243ad6d2e9fcd634862dda9003883484024fd2e067fc7e4a0f6c524cb6c86e";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.16.0-dev.27+83f773fc6.tar.xz";
      shasum = "658241c15ad827a89878b2e35e13261cd1c2aaefe9a8bb94ccb907725cf80564";
    };
    armv7l-linux = {
      filename = "zig-arm-linux-0.16.0-dev.27+83f773fc6.tar.xz";
      shasum = "6039c11f41bd032ec3cbda2d92e38b409aa9d9e2935b21266033b820ecb1a668";
    };
    i686-linux = {
      filename = "zig-x86-linux-0.16.0-dev.27+83f773fc6.tar.xz";
      shasum = "6eafb1b1d81118066dc03b17bed6612d7a9da057794f1d0f2451c249cf8a231d";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.16.0-dev.27+83f773fc6.tar.xz";
      shasum = "0562fdd578b5ae65a17e614454e67466314790a1d373279a4b054398f6a7b364";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.16.0-dev.27+83f773fc6.tar.xz";
      shasum = "f56712849af75bb1bfda502c8cdfc52dcc41c18d3d7eddd329d94be85538d258";
    };
    src = {
      filename = "zig-0.16.0-dev.27+83f773fc6.tar.xz";
      shasum = "afddafbede9becaa6d94a544d3115893cc6aa6492a58545b4f638c58990586dc";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.16.0-dev.27+83f773fc6.tar.xz";
      shasum = "1ac88b947a6001eb30d41c15c404847209dfe945a27dbce6d1b7d401e4aef325";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.16.0-dev.27+83f773fc6.tar.xz";
      shasum = "989caf4343e1dfb4c9a68f3d3146cac96729e6f6e58276001654307f56c43981";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.16.0-dev.27+83f773fc6.tar.xz";
      shasum = "c260aefaf5bf10bbd48101217874ccc9c0a37513729dabbbfe09bcf18fff1b5b";
    };
  }
  {
    _date = "2025-08-26";
    _version = "0.16.0-dev.38+37f4bee92";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.16.0-dev.38+37f4bee92.tar.xz";
      shasum = "6d7e6b98797db833629ae79feca376fc5b144e8608f27881d976d6d465a84847";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.16.0-dev.38+37f4bee92.tar.xz";
      shasum = "ba7ccc4bd4e594c08996b022dc4767cd8a0bb3416e661400db7799e611ad25c9";
    };
    armv7l-linux = {
      filename = "zig-arm-linux-0.16.0-dev.38+37f4bee92.tar.xz";
      shasum = "df1328e517712697647fc16165c21b01a744371b38fcedc55585d687595d35fa";
    };
    i686-linux = {
      filename = "zig-x86-linux-0.16.0-dev.38+37f4bee92.tar.xz";
      shasum = "f16676c6bbe304fd4f6d8390afc23ba4abe053b48232dd58747eb73677743797";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.16.0-dev.38+37f4bee92.tar.xz";
      shasum = "d038f6cab1e5ea6cf4a6a82d13e16c04505c2c720f3a2be111628d48896d0465";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.16.0-dev.38+37f4bee92.tar.xz";
      shasum = "6527bfee809bfb0f4aa606380ca486140e934753840a3a3862e93938ef2e1f1e";
    };
    src = {
      filename = "zig-0.16.0-dev.38+37f4bee92.tar.xz";
      shasum = "ffebde89227c878425e0f20c1855beb8ac9995c088e622691d88505d733aeda8";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.16.0-dev.38+37f4bee92.tar.xz";
      shasum = "f8e12dbf10e8dac6227c57fc742f9fd73e96a3823136aa6023377a9828af2f86";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.16.0-dev.38+37f4bee92.tar.xz";
      shasum = "7f95bacc0bc545177fe78756e80a31acefe9324e22717cc9ac7271d70dafa94d";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.16.0-dev.38+37f4bee92.tar.xz";
      shasum = "3d9df31c24b407a94c9165bb27676dba3fa67f380926391a0a7eafd9e91e1534";
    };
  }
  {
    _date = "2025-08-27";
    _version = "0.16.0-dev.48+aae556071";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.16.0-dev.48+aae556071.tar.xz";
      shasum = "e4a3c060fd26fad8a2b9e46c5732aa4cd628b240f8d165b54c5cdc9af5fcffd9";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.16.0-dev.48+aae556071.tar.xz";
      shasum = "27c81359bc4ec22c07d9f78724f8f379353f0eca02bc03d706333c915c197843";
    };
    armv7l-linux = {
      filename = "zig-arm-linux-0.16.0-dev.48+aae556071.tar.xz";
      shasum = "f60b95619a3780f1e848785c62ee372830c84d83fd5c7c9227db1ef5f1d2ea9a";
    };
    i686-linux = {
      filename = "zig-x86-linux-0.16.0-dev.48+aae556071.tar.xz";
      shasum = "b3913f8d2c13d680c319e48fbd341e85dc021a4c9f7fd8dcf3c39df73f858765";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.16.0-dev.48+aae556071.tar.xz";
      shasum = "977d5ee519ad34b5e78b0786751228d50c4fa125ac9b882810c57aa7c8f25b1c";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.16.0-dev.48+aae556071.tar.xz";
      shasum = "3acea5818a513e3f735cc54c30ee24f274d70e20684cd77cd8bc85f588ccd6e4";
    };
    src = {
      filename = "zig-0.16.0-dev.48+aae556071.tar.xz";
      shasum = "f2d4645c8a06143a4cded2601dea7bd42d3282c33fdc1557fad45ee48a31821a";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.16.0-dev.48+aae556071.tar.xz";
      shasum = "074cb6190c5266375692f3c0278e600021dd60b2d7d93388c074bedcf235f095";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.16.0-dev.48+aae556071.tar.xz";
      shasum = "7479b09781673178ab251011eb50cedad94549dff9ef6d0040abbb1894470c37";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.16.0-dev.48+aae556071.tar.xz";
      shasum = "e56b528f7e19511396b072677ea7611b2e20bd95f80f908c7f51102f0e230e46";
    };
  }
  {
    _date = "2025-08-28";
    _version = "0.16.0-dev.65+ca2e17e0a";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.16.0-dev.65+ca2e17e0a.tar.xz";
      shasum = "e21927862d229fd07fde143d5b620062d9c818d5f10514f498991943a5918c18";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.16.0-dev.65+ca2e17e0a.tar.xz";
      shasum = "a8da23e1b077cfd44f90b2e36e6371e503285a1541954b856fdf3a56cae1fbaa";
    };
    armv7l-linux = {
      filename = "zig-arm-linux-0.16.0-dev.65+ca2e17e0a.tar.xz";
      shasum = "f61d89aaccc9928bc4f888c742472468851c2c67fcf1bdfac8243dca4a9ed24a";
    };
    i686-linux = {
      filename = "zig-x86-linux-0.16.0-dev.65+ca2e17e0a.tar.xz";
      shasum = "6a88ca7530333ed0f0bff722b80a92233c4771605e46355112de303fe32eb445";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.16.0-dev.65+ca2e17e0a.tar.xz";
      shasum = "9c2283b33efa5af81bee8425c20583c79f582d212fb0100850da6f09209dadac";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.16.0-dev.65+ca2e17e0a.tar.xz";
      shasum = "cdbbb6178f95d9082006aa63addc2490cf697bf2d5f53a3892f7931aa9979cdf";
    };
    src = {
      filename = "zig-0.16.0-dev.65+ca2e17e0a.tar.xz";
      shasum = "56badd014f49e404ddea064f1d799d98a89d372794d01cc6fd00c285834e0c23";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.16.0-dev.65+ca2e17e0a.tar.xz";
      shasum = "35fefee44967dc8fdb801c7865a3068bcb51ff3745efbfb215b81862bb74d822";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.16.0-dev.65+ca2e17e0a.tar.xz";
      shasum = "56c8a21e9040b87916f521a312c9de1b8fe62d4feed8948216740db34f8c6583";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.16.0-dev.65+ca2e17e0a.tar.xz";
      shasum = "b8dbb17fc2d10135e1f2f9490ab75c5c7afb8bbb55c44411dd710ba572399c40";
    };
  }
  {
    _date = "2025-08-29";
    _version = "0.16.0-dev.70+73a0b5441";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.16.0-dev.70+73a0b5441.tar.xz";
      shasum = "16add5e6b8dd3a57a15772df9e591f41e93fc8132e61c0c8d5c086d062b05ebf";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.16.0-dev.70+73a0b5441.tar.xz";
      shasum = "0b89c55bae382df21534906a1941fdb835c6edd8ac503e71776b64d6a368d0fe";
    };
    armv7l-linux = {
      filename = "zig-arm-linux-0.16.0-dev.70+73a0b5441.tar.xz";
      shasum = "19ec585842a7172ed16a97f65f629cddc0b99690c1eaf5a557f6b393d66c71fc";
    };
    i686-linux = {
      filename = "zig-x86-linux-0.16.0-dev.70+73a0b5441.tar.xz";
      shasum = "7d5d544f1badd2b0df234c7418b40e166af2ec31c07c9ac8665193d5a756088f";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.16.0-dev.70+73a0b5441.tar.xz";
      shasum = "bddb10e87ef0e625ff9d3817dccfb0e74c0c546cb78258d0c53f8ea5b1ee3b1a";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.16.0-dev.70+73a0b5441.tar.xz";
      shasum = "121a23e739babd759412f4def0b80427a2cfc783183bf4f86fd6700df2a75fd1";
    };
    src = {
      filename = "zig-0.16.0-dev.70+73a0b5441.tar.xz";
      shasum = "d0a9354c135943f7f2d2e4a7bb2a08f8f1a8269d413dbc3716900aaa936a933c";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.16.0-dev.70+73a0b5441.tar.xz";
      shasum = "f233125a5a38c2f4f2c01468035dedb844c996bf85a2d2e8f9a21fcdb07d30f6";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.16.0-dev.70+73a0b5441.tar.xz";
      shasum = "68af705a1990dc6fd2bd34aee8ae1e86b9fd2df52b1827db10d01fdde8f1496c";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.16.0-dev.70+73a0b5441.tar.xz";
      shasum = "a67909aad016c9c3a62e71cdb4a538d9489aac9c4980e0e1975f4c87bba0c626";
    };
  }
  {
    _date = "2025-09-02";
    _version = "0.16.0-dev.164+bc7955306";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.16.0-dev.164+bc7955306.tar.xz";
      shasum = "56681d1c63a06f7ebd305e6ff3bc2a4f290038c76864310169155d6d07b64c24";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.16.0-dev.164+bc7955306.tar.xz";
      shasum = "5df9151ef404ca163cbabf8157641dc0b1e5783b66f76f938566c813d481ad59";
    };
    armv7l-linux = {
      filename = "zig-arm-linux-0.16.0-dev.164+bc7955306.tar.xz";
      shasum = "1547388a2e3da6eef9a068c820c3f42d368126c817b3d72a69cd4858b2df5c1a";
    };
    i686-linux = {
      filename = "zig-x86-linux-0.16.0-dev.164+bc7955306.tar.xz";
      shasum = "cdd9285e0396b0e501c5ee952b9dcad199235359e09a6da2467b72ebdee8a5cc";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.16.0-dev.164+bc7955306.tar.xz";
      shasum = "2e594762627ad2df8aea6eedcf58d208956d15b7223830bf148a9f630090b5ef";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.16.0-dev.164+bc7955306.tar.xz";
      shasum = "d68885aad5fd0bf71cdd51031fe543c703dc57d4e6ca4347045971160167d691";
    };
    src = {
      filename = "zig-0.16.0-dev.164+bc7955306.tar.xz";
      shasum = "b694a45433bff7876caabd8c251603d065339615070122c62dd7a3c8810aebdc";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.16.0-dev.164+bc7955306.tar.xz";
      shasum = "2706f8b6a258a61cda4f306eee9068968f613c627d04300855ddecadf15fcded";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.16.0-dev.164+bc7955306.tar.xz";
      shasum = "801a153cef410b5861614f2211487b6a0b3c96823b44e4234aeada2ec6bc01fc";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.16.0-dev.164+bc7955306.tar.xz";
      shasum = "020982a37d742f3c43a78af01367e639e70cfc2db02f092cf2df960d62a28079";
    };
  }
  {
    _date = "2025-09-03";
    _version = "0.16.0-dev.168+d51d18c98";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.16.0-dev.168+d51d18c98.tar.xz";
      shasum = "2be28e01188b396cc73fff1815fdf0593ff51646beb2c70d9b1c3a9bdd351cb2";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.16.0-dev.168+d51d18c98.tar.xz";
      shasum = "8780038fb5f2dc8e703b01994a45b8b31140b70c5fafdc3a2465082e54b0fb7d";
    };
    armv7l-linux = {
      filename = "zig-arm-linux-0.16.0-dev.168+d51d18c98.tar.xz";
      shasum = "61ccce111d279692cefb4668ed08f21b38b0c9e941672ee37d92a2c632f23bf8";
    };
    i686-linux = {
      filename = "zig-x86-linux-0.16.0-dev.168+d51d18c98.tar.xz";
      shasum = "f0503c29d9935f3073c4705641cc2caf6a6653dccaa4cca6875134217c7d7cf7";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.16.0-dev.168+d51d18c98.tar.xz";
      shasum = "285aa4e4125c714c6df8e36dd8767c8eded89031fbc96a691e074713f918cdf3";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.16.0-dev.168+d51d18c98.tar.xz";
      shasum = "2467eb7e14ad579567b42c776fae1cc72101ef07851e5b2897aef99e039e0342";
    };
    src = {
      filename = "zig-0.16.0-dev.168+d51d18c98.tar.xz";
      shasum = "7918012bc07dff68090f9502c4b4484ba44fc3e3f6602d8a961289656d933937";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.16.0-dev.168+d51d18c98.tar.xz";
      shasum = "ab9b7af140bdf02b6b1b3068b99080f9314bd3246dc37c3a938932edc707cd83";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.16.0-dev.168+d51d18c98.tar.xz";
      shasum = "b691bac8a67a18721c59cc135c42465ca450c0c682b7aecf46973b921f848cc9";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.16.0-dev.168+d51d18c98.tar.xz";
      shasum = "fafbb691632a7d57d3fee9cb0acde53f611c2a267d66cb5be2bbed3de59a043b";
    };
  }
  {
    _date = "2025-09-04";
    _version = "0.16.0-dev.178+b1189ab03";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.16.0-dev.178+b1189ab03.tar.xz";
      shasum = "841a55053b02d956cd9180e051f65e9b50e9808e33dd0d084fe2e285218a97ca";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.16.0-dev.178+b1189ab03.tar.xz";
      shasum = "4370c811c15bf64b0404a6b6409a15043f53abd5ad03acb3f7b84254aaa051dc";
    };
    armv7l-linux = {
      filename = "zig-arm-linux-0.16.0-dev.178+b1189ab03.tar.xz";
      shasum = "3b58e74f4b9097683b7edaa0c47d6da954a67e0d73c8ea9b647a6f7c1fcf12d0";
    };
    i686-linux = {
      filename = "zig-x86-linux-0.16.0-dev.178+b1189ab03.tar.xz";
      shasum = "fb47f6287f5133a66ff7d44b6fbbcb72e605f1bf9e764779795bb8486b776737";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.16.0-dev.178+b1189ab03.tar.xz";
      shasum = "8539fbe8026278a3616b7707507d3fbd4d02163d5d457393e4875f250a284505";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.16.0-dev.178+b1189ab03.tar.xz";
      shasum = "f2e8ea68f82caec4d8594c86f623eefdf48930256f8e8dd04a8935f1bf3bdb00";
    };
    src = {
      filename = "zig-0.16.0-dev.178+b1189ab03.tar.xz";
      shasum = "1bb14908b9c56fe027747488f81888fc8707855927a17e318414907a98731219";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.16.0-dev.178+b1189ab03.tar.xz";
      shasum = "150aec1101d843146b4ce2dcac2bf1e9d2086e2e05f54a17fd6bb659a2e1e527";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.16.0-dev.178+b1189ab03.tar.xz";
      shasum = "1606fba157834f30a8d61328efa6f284aad868ff8e9210b2fc43291ae266e12c";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.16.0-dev.178+b1189ab03.tar.xz";
      shasum = "ab38c5d1a0ca0ab0282f47c1b35f094469680caf03253b9e3e539b9bb382dc49";
    };
  }
  {
    _date = "2025-09-05";
    _version = "0.16.0-dev.191+9fa2394f8";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.16.0-dev.191+9fa2394f8.tar.xz";
      shasum = "8f70d863c4b8947c2bf67192aeb5f68fc30067b52158178c3dce2352d003fe9a";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.16.0-dev.191+9fa2394f8.tar.xz";
      shasum = "0e1b1d625ccc1df80bf2aabceeb3e309e48df092c0ac9a55285c3f10864a6d65";
    };
    armv7l-linux = {
      filename = "zig-arm-linux-0.16.0-dev.191+9fa2394f8.tar.xz";
      shasum = "112bb64f133af92b79da7b6c8889fb11b3c6f9a11ea037f35b695401eb0d000c";
    };
    i686-linux = {
      filename = "zig-x86-linux-0.16.0-dev.191+9fa2394f8.tar.xz";
      shasum = "f001d6aa5a78d8b88a25b61d8edfc23eec8093bb90178c7523e9f4ea7da1b71b";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.16.0-dev.191+9fa2394f8.tar.xz";
      shasum = "16f5a3f2b2bcc1dc97dde8df50e0e684539aed1dfd415d8eb7c48c93fc71c5f0";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.16.0-dev.191+9fa2394f8.tar.xz";
      shasum = "2a6946c9222d8a41db0f44eb04eadc526f2abdb80374f10d7176cde9608fe0ea";
    };
    src = {
      filename = "zig-0.16.0-dev.191+9fa2394f8.tar.xz";
      shasum = "4f11f06e2b84bb7742e74afad3543b4da8efbcce44a8865c725b33297fd06c01";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.16.0-dev.191+9fa2394f8.tar.xz";
      shasum = "2a8d14fc815ac44498c0afddcb4f27e5e0ec38238d4ca1e233a2aecb208c22a6";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.16.0-dev.191+9fa2394f8.tar.xz";
      shasum = "76e9ffd527e62ce0e47aeabeed8932454b993c1e150508dccfa2e5d605446f60";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.16.0-dev.191+9fa2394f8.tar.xz";
      shasum = "cd80d36383d0efc524f380b72444ad5063dc43166c4f5e31bd92668bfe0ad1d3";
    };
  }
  {
    _date = "2025-09-06";
    _version = "0.16.0-dev.197+1a5cf072a";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.16.0-dev.197+1a5cf072a.tar.xz";
      shasum = "29c3411dd0e223b2e7634d3fb1a65a411399a243e53bb7cfdd6621fdf8d7c013";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.16.0-dev.197+1a5cf072a.tar.xz";
      shasum = "8912d49ed1c88c6921dc36d78da202c3205bddd61c803e63ec38a3d3ac4210be";
    };
    armv7l-linux = {
      filename = "zig-arm-linux-0.16.0-dev.197+1a5cf072a.tar.xz";
      shasum = "515264140f0e34e902b54e8818ea0fd1215d9657096191ccac665ab5741a4f42";
    };
    i686-linux = {
      filename = "zig-x86-linux-0.16.0-dev.197+1a5cf072a.tar.xz";
      shasum = "f65aba569d09c6702333e151f8b8e77492d6389b25982c60de5a1ce4d8d8ad91";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.16.0-dev.197+1a5cf072a.tar.xz";
      shasum = "03c1ab1f4c0d2e5038a75f94f547807f3befb1c4e6259f252beb6d8e521b68f3";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.16.0-dev.197+1a5cf072a.tar.xz";
      shasum = "d318b9e1a2a54be3f8ed5ea0ef4d7c8611d7bb6c19d50eb44fb50183863a254e";
    };
    src = {
      filename = "zig-0.16.0-dev.197+1a5cf072a.tar.xz";
      shasum = "79426c82523a59be9c1a188682c727271d22eb32031c341bed3ede99c11aa7e0";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.16.0-dev.197+1a5cf072a.tar.xz";
      shasum = "5471f872ac8a84f0f7fb2a677edbc32096648dd1e4c9260f9651e63c51d670d0";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.16.0-dev.197+1a5cf072a.tar.xz";
      shasum = "f6c4caa5bad38be895e35d81d39e2ab960204ebda9eaf6f29de0369f555529d8";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.16.0-dev.197+1a5cf072a.tar.xz";
      shasum = "558f094c308d711d54ab163a2d8500f3436f2e9aefd56db8fd53d35297061d80";
    };
  }
  {
    _date = "2025-09-07";
    _version = "0.16.0-dev.205+4c0127566";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.16.0-dev.205+4c0127566.tar.xz";
      shasum = "3137aa29553e1804d0d480b484249922506eb027e1390e6ac649a9d5cdda9f89";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.16.0-dev.205+4c0127566.tar.xz";
      shasum = "a7739f8e3396c1c01cd61bc74753d64cb18742f9942d944a744897df4c9b23f8";
    };
    armv7l-linux = {
      filename = "zig-arm-linux-0.16.0-dev.205+4c0127566.tar.xz";
      shasum = "0785dff22d71947be1fe043b18b3d1aaeee44a76ec10bc31d3f18d4bb5ea6ec1";
    };
    i686-linux = {
      filename = "zig-x86-linux-0.16.0-dev.205+4c0127566.tar.xz";
      shasum = "11e58da3cf931749ebf475a3fc6adfe2284084e13552f3eaa3b6d43cba5c1080";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.16.0-dev.205+4c0127566.tar.xz";
      shasum = "f9002cba08d6c1904efd5e946512ec2d1a4c756fa040d73702f5d4766cfc008b";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.16.0-dev.205+4c0127566.tar.xz";
      shasum = "d7e4c426fe4658e68d977e0e7e4691aa32d37d29b3d59d282332bb2384f5558b";
    };
    src = {
      filename = "zig-0.16.0-dev.205+4c0127566.tar.xz";
      shasum = "42396fe0a7d9dc97bb781bd02a67c9c02bc260568ae82ff947b9a9b2d50b5ae6";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.16.0-dev.205+4c0127566.tar.xz";
      shasum = "10f53019888a8d63ab8f5ba3efee693e2041358d89e36e2d9b4c7817256913cf";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.16.0-dev.205+4c0127566.tar.xz";
      shasum = "3a1ad6f94a90912a6cc3e9e82531037f6198aa8562f2ed0acd96fe134d08c9f5";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.16.0-dev.205+4c0127566.tar.xz";
      shasum = "4e14927056addeec2020b3f43e4e35281c8bcd76786ed21484a7b042932a7492";
    };
  }
  {
    _date = "2025-09-09";
    _version = "0.16.0-dev.218+1872c85ac";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.16.0-dev.218+1872c85ac.tar.xz";
      shasum = "dc79512e71d7d67937ce6e24dd09c87f99467773d1d98411d24836defb4e89c3";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.16.0-dev.218+1872c85ac.tar.xz";
      shasum = "6ad7d645e3e2503a9feb98e1c56b24805bb2e20d99ac46ba6e0201ca26211472";
    };
    armv7l-linux = {
      filename = "zig-arm-linux-0.16.0-dev.218+1872c85ac.tar.xz";
      shasum = "1b2df021f1b5a9b6d5d6cc73ea5730b454e737f2b766e7aca6bae10b53533eb1";
    };
    i686-linux = {
      filename = "zig-x86-linux-0.16.0-dev.218+1872c85ac.tar.xz";
      shasum = "a1420247d67859d7dac070c936e090aadfeceace1aac936ba66532d49289a936";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.16.0-dev.218+1872c85ac.tar.xz";
      shasum = "ddfbce7527f081b15463b012052b76475c2a6f0cf5e0355df8f8a3597005bc62";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.16.0-dev.218+1872c85ac.tar.xz";
      shasum = "d7a8a1411d0968355ff0cb993d9bd4dc9080c54a0b16cad5ff96dd9750f34626";
    };
    src = {
      filename = "zig-0.16.0-dev.218+1872c85ac.tar.xz";
      shasum = "a70a8c5383afa94be79dcc06aca907a1505203cd504bed0136035dbb04256b7c";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.16.0-dev.218+1872c85ac.tar.xz";
      shasum = "97fc1a8758abfcb89ec3c814b38cf91ec5bef7142cfe69bcf2cfac24bf90d101";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.16.0-dev.218+1872c85ac.tar.xz";
      shasum = "bc58da6efae9e508002c95a657888230137e98e671c8fd688505fcf29588ec82";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.16.0-dev.218+1872c85ac.tar.xz";
      shasum = "32d1f40e27ffe68a2b73cde50bc5f37b727f87a341438f5132cadf1aaef3ae9c";
    };
  }
]
