# Autogenerated by update-releases.sh, do not modify
[
  {
    _date = "2025-08-13";
    _version = "0.15.0-dev.1519+dd4e25cf4";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.15.0-dev.1519+dd4e25cf4.tar.xz";
      shasum = "fe83c7ca585d375ad649bd22d76da3e83d61a1cd465b8e737c839ef5cb44f44f";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.15.0-dev.1519+dd4e25cf4.tar.xz";
      shasum = "75421d138aa17f3c6104b39ce5a2adef2fda933e58d6818a5f77ff3bde27c9bc";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.15.0-dev.1519+dd4e25cf4.tar.xz";
      shasum = "3bc50871c16d628d3717ed95829b47177eecb0f517a7a9061e6b860db18c719a";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.15.0-dev.1519+dd4e25cf4.tar.xz";
      shasum = "5c26cfa5e00be7c05cc5a73f2a1e45724044066fb62e05d9d1dd1cf9c3e2c2c4";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.15.0-dev.1519+dd4e25cf4.tar.xz";
      shasum = "26179d9fc1cb93c1e7fc2acb283f3a0ff17f2a57dda60e2f8d251c935472263a";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.15.0-dev.1519+dd4e25cf4.tar.xz";
      shasum = "ab6acf777cffe164b8636a2631f43cb45b4e2e057c15302b5093bdf360209bec";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.15.0-dev.1519+dd4e25cf4.tar.xz";
      shasum = "b23365e23487b1dfcdbe0b551d9ede361d78bfb959c31fa423717ded69c80375";
    };
  }
  {
    _date = "2025-08-14";
    _version = "0.15.0-dev.1552+b87b95868";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.15.0-dev.1552+b87b95868.tar.xz";
      shasum = "31a4110c3d5070192be76944ba18159a43ba1d86abc930a162b4d562c5517746";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.15.0-dev.1552+b87b95868.tar.xz";
      shasum = "2f583d9f9b3957209bbcef0d052fdde47b5b5598823879b210925863b25c867c";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.15.0-dev.1552+b87b95868.tar.xz";
      shasum = "e50088bcb721b38e2942e2345f5851cc710720adc9a2caf686cc6a530c3fa2ed";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.15.0-dev.1552+b87b95868.tar.xz";
      shasum = "8d56c7b990cc2851e119b5dc82271507c7285ccf6583cc79c62b809b59a137f0";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.15.0-dev.1552+b87b95868.tar.xz";
      shasum = "38aab57b554567f6ef5dce6fcbd7470d63b93decc2046ed022224c62db0e8ea2";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.15.0-dev.1552+b87b95868.tar.xz";
      shasum = "c8d5fd9df6f50db377f3791d2be876fa963c140645ed8412659adcdbd3e31396";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.15.0-dev.1552+b87b95868.tar.xz";
      shasum = "91284b7bca4b828cc1e9f769bc60de151f1fff8d0d4f162f04aab1c6c523e945";
    };
  }
  {
    _date = "2025-08-15";
    _version = "0.15.0-dev.1564+2761cc8be";
    aarch64-darwin = {
      filename = "zig-aarch64-macos-0.15.0-dev.1564+2761cc8be.tar.xz";
      shasum = "949d8a14b3efc1a5cf4a8dad68c91f6c2bb8dc8087adaccf72cd250ea1e221a0";
    };
    aarch64-linux = {
      filename = "zig-aarch64-linux-0.15.0-dev.1564+2761cc8be.tar.xz";
      shasum = "eea59d69dbd1789d471d24d157fe44765cdf0cd9de29520b103725b5fdd1a5e0";
    };
    powerpc64le-linux = {
      filename = "zig-powerpc64le-linux-0.15.0-dev.1564+2761cc8be.tar.xz";
      shasum = "c27b1c006d5811b2087046c69cf72acf109b76d6bcc4883ce01bc9a377d772d1";
    };
    riscv64-linux = {
      filename = "zig-riscv64-linux-0.15.0-dev.1564+2761cc8be.tar.xz";
      shasum = "62550ef3d80c3fab2c2c90c23de9b2025d0e32b6177502ddc9bafd4d9fb76ee9";
    };
    x86_64-darwin = {
      filename = "zig-x86_64-macos-0.15.0-dev.1564+2761cc8be.tar.xz";
      shasum = "10b1690c266e18b6fe1bc57c29aa16f1c68a5af14667152204936a8a3dece834";
    };
    x86_64-freebsd = {
      filename = "zig-x86_64-freebsd-0.15.0-dev.1564+2761cc8be.tar.xz";
      shasum = "47dc2428c216f2823188db831b1578bc2f338acfa9b5aa3200b63feea042b53d";
    };
    x86_64-linux = {
      filename = "zig-x86_64-linux-0.15.0-dev.1564+2761cc8be.tar.xz";
      shasum = "f6c23e66a15bfe1f2d1781a8d3604c275bee80318aa18cf139478baac114e2d1";
    };
  }
]
