# Autogenerated by update-releases.sh, do not modify
[
  {
    _date = "2024-06-08";
    _version = "0.12.0";
    aarch64-darwin = {
      shasum = "48892e8e75ebd8cbe1d82548e20094c4c9f7f1b81fdabe18b430f334d93dc76c";
      tarball = "https://builds.zigtools.org/zls-macos-aarch64-0.12.0.tar.xz";
    };
    aarch64-linux = {
      shasum = "ea81ee5c64c8b39aaf23c26d641e263470738d76bee945db9f7207bad10f6d6f";
      tarball = "https://builds.zigtools.org/zls-linux-aarch64-0.12.0.tar.xz";
    };
    i686-linux = {
      shasum = "f9ed28d9eb12701b85aafd1956d0d2622086a11761a68561de26677f6410ae6c";
      tarball = "https://builds.zigtools.org/zls-linux-x86-0.12.0.tar.xz";
    };
    x86_64-darwin = {
      shasum = "6c6b24d2d57de6fcae8c44d8c484a359262b4a46339fe339a6fade433fc7c6b6";
      tarball = "https://builds.zigtools.org/zls-macos-x86_64-0.12.0.tar.xz";
    };
    x86_64-linux = {
      shasum = "a1049798c9d3b14760f24de5c0a6b5a176abd404979828342b7319939563dfaa";
      tarball = "https://builds.zigtools.org/zls-linux-x86_64-0.12.0.tar.xz";
    };
  }
  {
    _date = "2024-06-08";
    _version = "0.11.0";
    aarch64-darwin = {
      shasum = "5152757727a958e6991b09fee4fb1b89c42b0e1c19f6b866e3567a83a126851c";
      tarball = "https://builds.zigtools.org/zls-macos-aarch64-0.11.0.tar.xz";
    };
    aarch64-linux = {
      shasum = "43184d2d324b27d2f18b72818676b367e6633264a0f4d74d1249b8a0824d1e1c";
      tarball = "https://builds.zigtools.org/zls-linux-aarch64-0.11.0.tar.xz";
    };
    i686-linux = {
      shasum = "580e8de3980778dc77aa0a77fb60efc0c71a17e12987f43379b326fc4c5dcf6c";
      tarball = "https://builds.zigtools.org/zls-linux-x86-0.11.0.tar.xz";
    };
    x86_64-darwin = {
      shasum = "8d3d83c8e1fc7a13d0c58624a9a0bdb289771c3714d01d7aace24277c95e70fb";
      tarball = "https://builds.zigtools.org/zls-macos-x86_64-0.11.0.tar.xz";
    };
    x86_64-linux = {
      shasum = "bd65d0cd79e83395b98035991b100821589b07ed8716fb2a44b1e234c9167f3f";
      tarball = "https://builds.zigtools.org/zls-linux-x86_64-0.11.0.tar.xz";
    };
  }
  {
    _date = "2024-06-08";
    _version = "0.10.0";
    aarch64-darwin = {
      shasum = "543c9f7d8895ab12b8c0b860601513c54d354ffd558a439fed9152af74c65ce6";
      tarball = "https://builds.zigtools.org/zls-macos-aarch64-0.10.0.tar.xz";
    };
    i686-linux = {
      shasum = "dfc6f2d791b84ff7bd7bfe24e17bc1fed430b6f2db7d8a31735fa19c892334e4";
      tarball = "https://builds.zigtools.org/zls-linux-x86-0.10.0.tar.xz";
    };
    x86_64-darwin = {
      shasum = "bebd917db44e8fff8daf5aab9f06dbee183dad1ce351bc6ecb264ccae710d951";
      tarball = "https://builds.zigtools.org/zls-macos-x86_64-0.10.0.tar.xz";
    };
    x86_64-linux = {
      shasum = "9a6cda8a9dc4b536f76439285541ad197eb30f67b0df47746411043c48091351";
      tarball = "https://builds.zigtools.org/zls-linux-x86_64-0.10.0.tar.xz";
    };
  }
  {
    _date = "2024-06-08";
    _version = "0.9.0";
    i686-linux = {
      shasum = "4596d0fcf236da331fa3afd9f282ac2492f22469f1b673465035b80850f4bd01";
      tarball = "https://builds.zigtools.org/zls-linux-x86-0.9.0.tar.xz";
    };
    x86_64-darwin = {
      shasum = "d8f2e8deda1751d7d46979b686784ebd5c843a9ba8f0bce69424351c4bfbea5f";
      tarball = "https://builds.zigtools.org/zls-macos-x86_64-0.9.0.tar.xz";
    };
    x86_64-linux = {
      shasum = "0bb16e2e3a1c4dab22b1d6b25deeefd2212abcc2e88702a3f58705164703a7f8";
      tarball = "https://builds.zigtools.org/zls-linux-x86_64-0.9.0.tar.xz";
    };
  }
  {
    _date = "2024-06-09";
    _version = "0.13.0";
    aarch64-darwin = {
      shasum = "9848514524f5e5d33997ac280b7d92388407209d4b8d4be3866dc3cf30ca6ca8";
      tarball = "https://builds.zigtools.org/zls-macos-aarch64-0.13.0.tar.xz";
    };
    aarch64-linux = {
      shasum = "8e258711168c2e3e7e81d6074663cfe291309b779928aaa4c66aed1affeba1aa";
      tarball = "https://builds.zigtools.org/zls-linux-aarch64-0.13.0.tar.xz";
    };
    i686-linux = {
      shasum = "9b1632f53528ec29b214286a6056ba1b352737335311926c48317daf1f73f234";
      tarball = "https://builds.zigtools.org/zls-linux-x86-0.13.0.tar.xz";
    };
    x86_64-darwin = {
      shasum = "4b63854d6b76810abd2563706e7d768efc7111e44dd8b371d49198e627697a13";
      tarball = "https://builds.zigtools.org/zls-macos-x86_64-0.13.0.tar.xz";
    };
    x86_64-linux = {
      shasum = "ec4c1b45caf88e2bcb9ebb16c670603cc596e4f621b96184dfbe837b39cd8410";
      tarball = "https://builds.zigtools.org/zls-linux-x86_64-0.13.0.tar.xz";
    };
  }
  {
    _date = "2025-03-06";
    _version = "0.14.0";
    aarch64-darwin = {
      shasum = "dfb627e1f9603583678f552d8035a12dce878215c0a507b32d6f1b9d074d6c4d";
      tarball = "https://builds.zigtools.org/zls-macos-aarch64-0.14.0.tar.xz";
    };
    aarch64-linux = {
      shasum = "d85f4679af3961db149ead8a355eab4652c3e738eecaad69174cab5f1a1196cc";
      tarball = "https://builds.zigtools.org/zls-linux-aarch64-0.14.0.tar.xz";
    };
    armv7l-linux = {
      shasum = "34a41ddf6790959b220724957dedd2919f276298277f3e985dc68c7f9b47d3a0";
      tarball = "https://builds.zigtools.org/zls-linux-armv7a-0.14.0.tar.xz";
    };
    i686-linux = {
      shasum = "79ca762b6cd5cffc165d473636fe0e1b225d2a4f75e5fed555261be4f046166b";
      tarball = "https://builds.zigtools.org/zls-linux-x86-0.14.0.tar.xz";
    };
    powerpc64le-linux = {
      shasum = "c5d88b19017d8b9904a03cb088521f5bbd17171214b84bf2e712947f975b5b9f";
      tarball = "https://builds.zigtools.org/zls-linux-powerpc64le-0.14.0.tar.xz";
    };
    riscv64-linux = {
      shasum = "892915a4b06b0503681e45eb45d7bf67a7d7d48daeb73c4ffd0bfb0d59b27a4b";
      tarball = "https://builds.zigtools.org/zls-linux-riscv64-0.14.0.tar.xz";
    };
    x86_64-darwin = {
      shasum = "baee69e4645deeccb42970b4a01f573592209dc1cf72e32893c59ca06af511dc";
      tarball = "https://builds.zigtools.org/zls-macos-x86_64-0.14.0.tar.xz";
    };
    x86_64-linux = {
      shasum = "661f8d402ba3dc9b04b6e9bc3026495be7b838d2f18d148db2bd98bd699c1360";
      tarball = "https://builds.zigtools.org/zls-linux-x86_64-0.14.0.tar.xz";
    };
  }
  {
    _date = "2025-08-24";
    _version = "0.15.0";
    aarch64-darwin = {
      shasum = "76c7a23190f67e67970024065f689c2c49b3c7b0fc16876fb24ef199fb05fc2a";
      tarball = "https://builds.zigtools.org/zls-aarch64-macos-0.15.0.tar.xz";
    };
    aarch64-linux = {
      shasum = "2d1c91382dbbd7a34c3bd87da506e3c2ce6e6582612c2b371f7f97b46c5557d4";
      tarball = "https://builds.zigtools.org/zls-aarch64-linux-0.15.0.tar.xz";
    };
    armv7l-linux = {
      shasum = "bcd86dc7d627c05ce4e1d212f2d88866af69a687b7cef5fbbf4f78d18e4f4d34";
      tarball = "https://builds.zigtools.org/zls-arm-linux-0.15.0.tar.xz";
    };
    i686-linux = {
      shasum = "a213e54be1e5aabf28a60fb55072f8d024a1b3d3a1ff2d6cf7132ba78db0892c";
      tarball = "https://builds.zigtools.org/zls-x86-linux-0.15.0.tar.xz";
    };
    powerpc64le-linux = {
      shasum = "67540b2fa539176b8f7cd1493f3b9da2518bd5028feebbab619dc40841a9a25d";
      tarball = "https://builds.zigtools.org/zls-powerpc64le-linux-0.15.0.tar.xz";
    };
    riscv64-linux = {
      shasum = "4c3331846935ce442c51131e9e4a56bba1a4d28e149da211870b15a4b342baea";
      tarball = "https://builds.zigtools.org/zls-riscv64-linux-0.15.0.tar.xz";
    };
    x86_64-darwin = {
      shasum = "46c31838bfef5adcc7fee82428c3ec2b9abbfae38242639afea5f242ee133d93";
      tarball = "https://builds.zigtools.org/zls-x86_64-macos-0.15.0.tar.xz";
    };
    x86_64-linux = {
      shasum = "508bfe3fd637d2a02f07f3fc7da8900351f407116b03685c5dae26b4f01a30de";
      tarball = "https://builds.zigtools.org/zls-x86_64-linux-0.15.0.tar.xz";
    };
  }
  {
    _date = "2025-12-05";
    _version = "0.15.1";
    aarch64-darwin = {
      shasum = "a6b3f1b10d77f37f3b9d962093f030334b083f48eb2607a4b3ccb72de2958133";
      tarball = "https://builds.zigtools.org/zls-aarch64-macos-0.15.1.tar.xz";
    };
    aarch64-linux = {
      shasum = "a2daa860a0e0cd1410491ff9703c6aaca96defd833b88af6a9811d6ff04fc13b";
      tarball = "https://builds.zigtools.org/zls-aarch64-linux-0.15.1.tar.xz";
    };
    armv7l-linux = {
      shasum = "4c57284eb605e51ed895e30a07c40579473f56390338af2caa35ce25a2264c8c";
      tarball = "https://builds.zigtools.org/zls-arm-linux-0.15.1.tar.xz";
    };
    i686-linux = {
      shasum = "b0a2fd145bd19ed274a4cd523cd682ba00894c549a083aef95cbbde7fa1a2c45";
      tarball = "https://builds.zigtools.org/zls-x86-linux-0.15.1.tar.xz";
    };
    powerpc64le-linux = {
      shasum = "3b1a55f3e811426f0845f9ea3e16246ecc2896f0e602e87b2959166a5e42aa63";
      tarball = "https://builds.zigtools.org/zls-powerpc64le-linux-0.15.1.tar.xz";
    };
    riscv64-linux = {
      shasum = "6ffd523b08b3b1c18ef061653e29e08e7561633c60dcd41f4af2e9985aa32daf";
      tarball = "https://builds.zigtools.org/zls-riscv64-linux-0.15.1.tar.xz";
    };
    x86_64-darwin = {
      shasum = "b76aa724be3f69799f08063f84e93b8b5925f6bf6007f251a2fbea4f9fc244dd";
      tarball = "https://builds.zigtools.org/zls-x86_64-macos-0.15.1.tar.xz";
    };
    x86_64-linux = {
      shasum = "3bb38f522cb23213e8c075ac6b170273fe49b4274b8c12b034cc496407400067";
      tarball = "https://builds.zigtools.org/zls-x86_64-linux-0.15.1.tar.xz";
    };
  }
]
