name: Build
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-latest-arm, macos-latest]
        version: ["", "-nightly", "-0.14.1", "-nightly-2025-08-13", "-0.9.0"]
        suffix: ["", ".fromSource"]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v31
      - run: nix run .#zig${{matrix.version}}${{matrix.suffix}} env
