name: Build
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v31
      - name: Build binary package
        run: nix run .#zig env
      - name: Build source package
        run: nix run .#zig.fromSource env
