name: Build
on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
          - macos-latest
        package:
          - .#default
          - .#nightly
          - .#zig_0_14_0
          - .#zig_0_9_0
          - .#zig_0_15_0_dev_1519

    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix run '${{matrix.package}}' env
