name: Build
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
          - macos-latest
        package:
          - default
          - zig_0_14_0
          - zig_0_9_0
          - zig_nightly
          - zig_nightly_2025_08_13

    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix run .#${{matrix.package}} env
